use crate::intern::{Interner};
use super::token_kind::TokenKind;

// Lookup table for XCX keywords.
pub fn lookup(text: &str, interner: &mut Interner) -> TokenKind {
    let lower_text = text.to_lowercase();
    
    // Map exact case-sensitive matches for set operations if needed, 
    // but XCX prefers case-insensitive for keywords except specific math constants.
    match text {
        "UNION" => return TokenKind::Union,
        "INTERSECTION" => return TokenKind::Intersection,
        "DIFFERENCE" => return TokenKind::Difference,
        "SYMMETRIC_DIFFERENCE" => return TokenKind::SymDifference,
        "HAS" => return TokenKind::Has,
        "AND" => return TokenKind::And,
        "OR" => return TokenKind::Or,
        "NOT" => return TokenKind::Not,
        "N" => return TokenKind::TypeSetN,
        "Q" => return TokenKind::TypeSetQ,
        "Z" => return TokenKind::TypeSetZ,
        "S" => return TokenKind::TypeSetS,
        "B" => return TokenKind::TypeSetB,
        "C" => return TokenKind::TypeSetC,
        _ => {}
    }

    match lower_text.as_str() {
        "const" => TokenKind::Const,
        "i" | "int" => TokenKind::TypeI,
        "f" | "float" => TokenKind::TypeF,
        "s" | "string" | "str" => TokenKind::TypeS,
        "b" | "bool" | "boolean" => TokenKind::TypeB,
        "true" => TokenKind::True,
        "false" => TokenKind::False,
        "if" => TokenKind::If,
        "then" => TokenKind::Then,
        "elseif" | "elif" | "elf" => TokenKind::ElseIf,
        "else" | "els" => TokenKind::Else,
        "end" => TokenKind::End,
        "for" => TokenKind::For,
        "in" => TokenKind::In,
        "to" => TokenKind::To,
        "while" => TokenKind::While,
        "do" => TokenKind::Do,
        "break" => TokenKind::Break,
        "continue" => TokenKind::Continue,
        "and" => TokenKind::And,
        "or" => TokenKind::Or,
        "not" => TokenKind::Not,
        "has" => TokenKind::Has,
        "halt" => TokenKind::Halt,
        "alert" => TokenKind::Alert,
        "error" => TokenKind::Error,
        "fatal" => TokenKind::Fatal,
        "terminal" => TokenKind::Terminal,
        "func" | "function" | "fun" => TokenKind::Func,
        "return" => TokenKind::Return,
        "array" => TokenKind::Array,
        "set" => TokenKind::Set,
        "map" => TokenKind::Map,
        "date" => TokenKind::Date,
        "store" => TokenKind::Store,
        "schema" => TokenKind::Schema,
        "data" => TokenKind::Data,
        "table" => TokenKind::Table,
        "database" => TokenKind::Database,
        "columns" => TokenKind::Columns,
        "rows" => TokenKind::Rows,
        "json" => TokenKind::Json,
        "net" => TokenKind::Net,
        "crypto" => TokenKind::Crypto,
        "env" => TokenKind::Env,
        "perf" => TokenKind::Perf,
        "serve" => TokenKind::Serve,
        "fiber" => TokenKind::Fiber,
        "yield" => TokenKind::Yield,
        "empty" => TokenKind::Empty,
        "include" => TokenKind::Include,
        "as" => TokenKind::As,
        "random" => TokenKind::Random,
        "choice" => TokenKind::Choice,
        "from" => TokenKind::From,
        _ => TokenKind::Identifier(interner.intern(text)),
    }
}
